services:
  publisher-service:
    image: publisher-api
    build: ./publisher-service/
    ports:
      - 7700:5000
    depends_on:
      - rabbitmq

  rabbitmq:
    image: docker.arvancloud.ir/rabbitmq:3.9-management-alpine
    ports:
      - 7701:15672
